<?php
/**
 * Most used timezones
 */

return  [
	'(GMT -11:00) Pacific/Midway'                => '(GMT-11:00) Midway Island, Samoa',
	'(GMT -10:00) Etc/GMT+10'                    => '(GMT-10:00) Hawaii',
	'(GMT -9:00) America/Anchorage'              => '(GMT-09:00) Alaska',
	'(GMT -8:00) America/Los_Angeles'            => '(GMT-08:00) Pacific Time (US & Canada)',
	'(GMT -8:00) America/Ensenada'               => '(GMT-08:00) Tijuana, Baja California',
	'(GMT -7:00) America/Denver'                 => '(GMT-07:00) Mountain Time (US & Canada)',
	'(GMT -7:00) America/Dawson_Creek'           => '(GMT-07:00) Arizona',
	'(GMT -6:00) America/Chicago'                => '(GMT-06:00) Central Time (US & Canada)',
	'(GMT -6:00) America/Mexico_City'            => '(GMT-06:00) Mexico City, Guadalajara',
	'(GMT -6:00) America/Belize'                 => '(GMT-06:00) Saskatchewan, Central America',
	'(GMT -5:00) America/New_York'               => '(GMT-05:00) Eastern Time (US & Canada)',
	'(GMT -5:00) America/Bogota'                 => '(GMT-05:00) Bogota, Lima, Quito, Rio Branco',
	'(GMT -4:00) Canada/Atlantic'                => '(GMT-04:00) Atlantic Time (Canada), Caracas',
	'(GMT -3:00) America/Sao_Paulo'              => '(GMT-03:00) Brazil',
	'(GMT -3:00) America/Argentina/Buenos_Aires' => '(GMT-03:00) Argentina',
	'(GMT -3:00) America/Montevideo'             => '(GMT-03:00) Uruguay',
	'(GMT -2:00) America/Noronha'                => '(GMT-02:00) Mid-Atlantic',
	'(GMT -1:00) Atlantic/Azores'                => '(GMT-01:00) Azores',
	'(GMT) Europe/London'                        => '(GMT) Western Europe Time, London, Lisbon, Casablanca',
	'(GMT +1:00) Europe/Brussels'                => '(GMT+01:00) Brussels, Copenhagen, Madrid, Paris',
	'(GMT +1:00) Europe/Amsterdam'               => '(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
	'(GMT +1:00) Europe/Belgrade'                => '(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
	'(GMT +2:00) Europe/Istanbul'                => '(GMT+02:00) Eastern European Time, Helsinki, Istanbul',
	'(GMT +2:00) Africa/Cairo'                   => '(GMT+02:00) Egypt',
	'(GMT +2:00) Africa/Blantyre'                => '(GMT+02:00) Harare, Pretoria',
	'(GMT +2:00) Asia/Jerusalem'                 => '(GMT+02:00) Jerusalem',
	'(GMT +3:00) Europe/Moscow'                  => '(GMT+03:00) Moscow, St. Petersburg, Volgograd',
	'(GMT +3:30) Asia/Tehran'                    => '(GMT +3:30) Tehran',
	'(GMT +4:00) Asia/Dubai'                     => '(GMT+04:00) Abu Dhabi, Muscat',
	'(GMT +5:00) Asia/Yekaterinburg'             => '(GMT+05:00) Ekaterinburg',
	'(GMT +5:00) Asia/Tashkent'                  => '(GMT +5:00) Tashkent',
	'(GMT +5:30) Asia/Kolkata'                   => '(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi',
	'(GMT +5:45) Asia/Katmandu'                  => '(GMT+05:45) Kathmandu',
	'(GMT +6:00) Asia/Dhaka'                     => '(GMT+06:00) Astana, Dhaka',
	'(GMT +7:00) Asia/Bangkok'                   => '(GMT+07:00) Bangkok, Hanoi, Jakarta',
	'(GMT +8:00) Asia/Hong_Kong'                 => '(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
	'(GMT +8:00) Australia/Perth'                => '(GMT+08:00) Perth',
	'(GMT +9:00) Asia/Tokyo'                     => '(GMT+09:00) Osaka, Sapporo, Tokyo',
	'(GMT +9:00) Asia/Seoul'                     => '(GMT+09:00) Seoul',
	'(GMT +9:30) Australia/Adelaide'             => '(GMT+09:30) Adelaide',
	'(GMT +9:30) Australia/Darwin'               => '(GMT+09:30) Darwin',
	'(GMT +10:00) Australia/Brisbane'            => '(GMT+10:00) Eastern Australia',
	'(GMT +11:00) Asia/Magadan'                  => '(GMT+11:00) Magadan, Solomon Islands, New Caledonia',
	'(GMT +12:00) Pacific/Auckland'              => '(GMT+12:00) Auckland, Wellington'
];